### ISSUE TITLE
Centralization

### ISSUE THREAD

**Issue by Nikesh16** [dahalnischal/Maxden-ai#2]
<img width="151" alt="Screenshot_204" src="https://github.com/dahalnischal/Maxden-ai/assets/68516996/6e8212fe-74d2-46f9-b5f4-9c3232d6e38f">
<img width="245" alt="Screenshot_206" src="https://github.com/dahalnischal/Maxden-ai/assets/68516996/91e3b699-ae95-4602-9c2f-da47b5e4359d">
<img width="206" alt="Screenshot_207" src="https://github.com/dahalnischal/Maxden-ai/assets/68516996/ebe732e4-f5ae-4b51-93e6-37032c77f7e6">
<img width="133" alt="Screenshot_208" src="https://github.com/dahalnischal/Maxden-ai/assets/68516996/5edbfb40-9d36-4ad4-9d0e-7af04953ae62">

**Comment by dahalnischal** [comment]
made button text to center
